#!/usr/bin/env bash
# 01_apt_update.sh — Update package repository
# Generated by investigate-playbook-planner
set -euo pipefail

# --- Color Codes ---
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# --- Helper Functions ---
check() {
    local status=$1
    local msg=$2
    if [ "$status" -eq 0 ]; then
        echo -e "  ${GREEN}✓${NC} $msg [PASS]"
    else
        echo -e "  ${RED}✗${NC} $msg [FAIL]"
        exit 1
    fi
}

header() {
    echo "----------------------------------------"
    echo "  $1"
    echo "----------------------------------------"
}

# --- Main Script ---
header "Phase 1: Update Package Repository"

echo "Running apt update..."
if command -v apt-get &>/dev/null; then
    apt-get update -y
    check 0 "Package repository updated"
else
    check 1 "apt-get not found - this script requires Debian/Ubuntu"
fi

echo ""
echo -e "${GREEN}Phase 1 completed successfully${NC}"