#!/usr/bin/env bash
# 02_install_docker.sh — Install Docker Engine
# Generated by investigate-playbook-planner
set -euo pipefail

# --- Color Codes ---
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# --- Helper Functions ---
check() {
    local status=$1
    local msg=$2
    if [ "$status" -eq 0 ]; then
        echo -e "  ${GREEN}✓${NC} $msg [PASS]"
    else
        echo -e "  ${RED}✗${NC} $msg [FAIL]"
        exit 1
    fi
}

header() {
    echo "----------------------------------------"
    echo "  $1"
    echo "----------------------------------------"
}

# --- Main Script ---
header "Phase 2: Install Docker"

DOCKER_PACKAGE="docker.io"

echo "Installing ${DOCKER_PACKAGE}..."
if command -v apt-get &>/dev/null; then
    apt-get install -y "$DOCKER_PACKAGE"
    check 0 "${DOCKER_PACKAGE} installed"
else
    check 1 "apt-get not found - this script requires Debian/Ubuntu"
fi

echo ""
echo "Verifying Docker installation..."
if command -v docker &>/dev/null; then
    DOCKER_VERSION=$(docker --version 2>/dev/null || echo "unknown")
    echo "  Docker version: $DOCKER_VERSION"
    check 0 "Docker binary found at $(which docker)"
else
    check 1 "Docker binary not found"
fi

echo ""
echo -e "${GREEN}Phase 2 completed successfully${NC}"