#!/usr/bin/env bash
# 03_enable_docker.sh — Enable Docker service
# Generated by investigate-playbook-planner
set -euo pipefail

# --- Color Codes ---
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# --- Helper Functions ---
check() {
    local status=$1
    local msg=$2
    if [ "$status" -eq 0 ]; then
        echo -e "  ${GREEN}✓${NC} $msg [PASS]"
    else
        echo -e "  ${RED}✗${NC} $msg [FAIL]"
        exit 1
    fi
}

header() {
    echo "----------------------------------------"
    echo "  $1"
    echo "----------------------------------------"
}

# --- Main Script ---
header "Phase 3: Enable Docker Service"

echo "Enabling Docker service to start on boot..."
if command -v systemctl &>/dev/null; then
    systemctl enable docker
    check 0 "Docker service enabled"
else
    check 1 "systemctl not found - this script requires systemd"
fi

echo ""
echo "Verifying Docker service is enabled..."
if systemctl is-enabled docker &>/dev/null; then
    check 0 "Docker service is enabled"
else
    check 1 "Docker service is NOT enabled"
fi

echo ""
echo -e "${GREEN}Phase 3 completed successfully${NC}"