#!/usr/bin/env bash
# audit_env.sh — Verify environment meets requirements
# Generated by investigate-playbook-planner
set -euo pipefail

# --- Color Codes ---
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# --- Helper Functions ---
check() {
    local status=$1
    local msg=$2
    if [ "$status" -eq 0 ]; then
        echo -e "  ${GREEN}✓${NC} $msg [PASS]"
    else
        echo -e "  ${RED}✗${NC} $msg [FAIL]"
        exit 1
    fi
}

header() {
    echo "----------------------------------------"
    echo "  $1"
    echo "----------------------------------------"
}

# --- Main Script ---
header "Environment Audit"

echo "Checking OS..."
if [ -f /etc/os-release ]; then
    . /etc/os-release
    echo "  OS: $NAME $VERSION"
    if [[ "$ID" == "ubuntu" || "$ID" == "debian" ]]; then
        check 0 "OS is Debian/Ubuntu-based"
    else
        echo -e "  ${YELLOW}!${NC} OS may not be compatible (expected Debian/Ubuntu)"
        check 0 "OS check completed with warnings"
    fi
else
    check 1 "Cannot determine OS"
fi

echo ""
echo "Checking CPU..."
CPU_CORES=$(nproc 2>/dev/null || echo 1)
echo "  CPU Cores: $CPU_CORES"
if [ "$CPU_CORES" -ge 1 ]; then
    check 0 "CPU meets minimum requirement (1 core)"
else
    check 1 "CPU does not meet minimum requirement"
fi

echo ""
echo "Checking Memory..."
if command -v free &>/dev/null; then
    TOTAL_MEM=$(free -m | awk '/^Mem:/{print $2}')
    echo "  Total Memory: ${TOTAL_MEM}MB"
    if [ "$TOTAL_MEM" -ge 512 ]; then
        check 0 "Memory meets minimum requirement (512MB)"
    else
        check 1 "Memory does not meet minimum requirement"
    fi
else
    echo -e "  ${YELLOW}!${NC} Cannot verify memory (free command not available)"
fi

echo ""
echo "Checking Disk Space..."
if command -v df &>/dev/null; then
    AVAILABLE=$(df -BG / | awk 'NR==2 {print $4}' | tr -d 'G')
    echo "  Available Disk: ${AVAILABLE}GB"
    if [ "$AVAILABLE" -ge 5 ]; then
        check 0 "Disk meets minimum requirement (5GB)"
    else
        check 1 "Disk does not meet minimum requirement"
    fi
else
    echo -e "  ${YELLOW}!${NC} Cannot verify disk space (df command not available)"
fi

echo ""
echo "Checking network connectivity..."
if command -v curl &>/dev/null; then
    if curl -s --max-time 5 http://archive.ubuntu.com/ >/dev/null 2>&1; then
        check 0 "Network connectivity OK"
    else
        echo -e "  ${YELLOW}!${NC} Cannot reach Ubuntu archive (network issue)"
        check 1 "Network connectivity check failed"
    fi
elif command -v ping &>/dev/null; then
    if ping -c 1 -W 3 8.8.8.8 &>/dev/null; then
        check 0 "Network connectivity OK"
    else
        echo -e "  ${YELLOW}!${NC} Network connectivity issue detected"
        check 1 "Network connectivity check failed"
    fi
else
    echo -e "  ${YELLOW}!${NC} Cannot verify network (no curl/ping available)"
fi

echo ""
echo -e "${GREEN}Environment audit completed successfully${NC}"
echo "You may proceed with the installation."