#!/usr/bin/env bash
# final_validation.sh — Validate Docker installation
# Generated by investigate-playbook-planner
set -euo pipefail

# --- Color Codes ---
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# --- Helper Functions ---
check() {
    local status=$1
    local msg=$2
    if [ "$status" -eq 0 ]; then
        echo -e "  ${GREEN}✓${NC} $msg [PASS]"
    else
        echo -e "  ${RED}✗${NC} $msg [FAIL]"
        exit 1
    fi
}

header() {
    echo "========================================"
    echo "  $1"
    echo "========================================"
}

# --- Main Script ---
header "Final Validation: Docker Installation"

FAILED=0

echo "1. Checking if Docker binary exists..."
if command -v docker &>/dev/null; then
    check 0 "Docker binary found"
else
    check 1 "Docker binary NOT found"
    FAILED=1
fi

echo ""
echo "2. Checking Docker service status..."
if command -v systemctl &>/dev/null; then
    if systemctl is-active docker &>/dev/null; then
        check 0 "Docker service is active"
    else
        echo -e "  ${YELLOW}!${NC} Docker service is not active (may need manual start)"
        check 1 "Docker service is not active"
        FAILED=1
    fi
else
    echo -e "  ${YELLOW}!${NC} systemctl not available, skipping service check"
fi

echo ""
echo "3. Checking Docker service enabled..."
if command -v systemctl &>/dev/null; then
    if systemctl is-enabled docker &>/dev/null; then
        check 0 "Docker service is enabled on boot"
    else
        check 1 "Docker service is NOT enabled"
        FAILED=1
    fi
else
    echo -e "  ${YELLOW}!${NC} systemctl not available, skipping enable check"
fi

echo ""
echo "4. Checking Docker version..."
if command -v docker &>/dev/null; then
    DOCKER_VERSION=$(docker --version 2>/dev/null || echo "unknown")
    echo "  $DOCKER_VERSION"
    check 0 "Docker version retrieved"
else
    check 1 "Cannot get Docker version"
    FAILED=1
fi

echo ""
header "Validation Summary"

if [ "$FAILED" -eq 0 ]; then
    echo -e "${GREEN}All checks passed! Docker is installed and configured correctly.${NC}"
    echo ""
    echo "Next steps:"
    echo "  - Run 'docker ps' to verify Docker is working"
    echo "  - You may need to log out and back in for Docker group permissions"
else
    echo -e "${RED}Some checks failed. Please review the errors above.${NC}"
    exit 1
fi